.gitconfig: Replace deprecated [a.b] with [a "b"] section definitions
The former is not just deprecated in Git, but generates an error from
the Golang `git-go` library as used by `git-bug` and presumably other
tools, producing errors like

    Error: unable to load system-scoped git config: 45:7: illegal character U+002E '.'

(The former also does some lowercasing and whatnot.)

For lots of gory details, see:
https://claude.ai/share/0bc3c0df-ebe7-468a-ad71-9f4ceef7f718